### ISSUE TITLE
Error ETIMEDOUT

### ISSUE THREAD

**Issue by PierrickRauby** [fivdi/mcp9808-temperature-sensor#1]
Hi, 
I am trying to use the example temperature.js directly from the mcp9808-temperature-sensor folder. I am receiving this error message every time:

Error: ETIMEDOUT, Connection timed out
    at Error (native)

Do you have any idea to solve this? 
Thanks

**Comment by fivdi** [comment]
Here's what the [I2C kernel documentation](https://www.kernel.org/doc/Documentation/i2c/fault-codes) has to say about `ETIMEDOUT`:
```
ETIMEDOUT
	This is returned by drivers when an operation took too much
	time, and was aborted before it completed.

	SMBus adapters may return it when an operation took more
	time than allowed by the SMBus specification; for example,
	when a slave stretches clocks too far.  I2C has no such
	timeouts, but it's normal for I2C adapters to impose some
	arbitrary limits (much longer than SMBus!) too.
```
What type of computer is the MCP9808 connected to?
Is the MCP9808 connected to I2C bus number 1 as this is what `temperature.js` expects?
Is the I2C address of the MCP9808 0x18 as this is what `temperature.js` expects?
Is there a stack trace printed with the error? If so, please post the complete output of the program.
What's the complete output of the command `i2cdetect -y -r 1`?
What's the complete output of the command `i2cget -y 1 0x18 0x06 w`?

**Comment by fivdi** [comment]
@PierrickRauby Your profile has a lot of BeagleBone Black repositories so I guess your seeing the issue on a BeagleBone Black.

Although `/dev/i2c-1` exists after booting a BeagleBone Black with Debian it has not been fully configured for usage. It's still necessary to configure the `i2c` mode for the appropriate pins on the GPIO headers with the `config-pin` utility.

As can be seen [here](http://beagleboard.org/static/images/cape-headers-i2c.png), I2C bus number 1 can be configured on pins P9.17, P9.18, P9.24 and p9.26.

Lets say I2C1_SCL should be on P9.17 and I2C1_SDA should be on P9.18. To perform this configuration the following commands need to be run:

```
config-pin P9.17 i2c
config-pin P9.18 i2c
```

Please give this a try and then run `temperature.js` to see if it then works.

**Comment by PierrickRauby** [comment]
Hi sorry for the delay ... 
You are right, i am using a BeagleBone Black.
It was my mistake I though I was using I2C-1 but it was not the case... sorry for the inconvenience. I change to I2C to try and it is working fine.
By the way I am using a cape on the BBB which only gave "easy access" to the I2C-2, do you think it will be easy to adapt your code to I2C-2, if yes i would be happy to do it. 

Thanks

**Comment by fivdi** [comment]
Yes, it's easy to adapt the code to use I2C-2. The documentation for [open](https://github.com/fivdi/mcp9808-temperature-sensor#openoptions) in the readme says that there is an option called `i2cBusNumber` which is used to specify the number of the I2C bus to use. If you would like to use I2C-2 rather than I2C-1 simply say this when calling `open`. For example, the following code can be used to read the temperature from an MCP9808 connected to I2C-2 and display the temperature on the screen
```js
const Mcp9808 = require('../');

let tempSensor;

Mcp9808.open({
  i2cBusNumber: 2, // <<<=== Specify I2C bus number here
  i2cAddress: 0x18
}).then((sensor) => {
  tempSensor = sensor;
  return tempSensor.temperature();
}).then((temp) => {
  console.log(temp.celsius + '°C');
  return tempSensor.close();
}).catch((err) => {
  console.log(err.stack);
});
```

I'm not fully sure if I understand your last comment. What I don't want to do is to change the example programs in this repository to use I2C-2. I want the example to stay as they are now and use I2C-1.

**Comment by fivdi** [comment]
@PierrickRauby Is it ok to close this issue?

**Comment by PierrickRauby** [comment]
Yes sure, thanks again for your help!
