### ISSUE TITLE
To a new student to node.js your example is completely confusing!

### ISSUE THREAD

**Issue by dachshund-digital** [fivdi/mcp9808-temperature-sensor#3]
To a new student to node.js your example is completely confusing!  It so de-referenced and abstracted it impossible to understand.  How about a simple example that does leverage javascript unique language features to the extreme?

**Comment by fivdi** [comment]
The `mcp9808-temperature-sensor` module relies on asynchronous promise-based behavior so familiarity with promises is going to be necessary if you would like to use `mcp9808-temperature-sensor`. The async and await keywords enable asynchronous promise-based behavior to be written in a cleaner style avoiding the need to explicitly configure promise chains.

Assuming that the example being referred to is this one:
```js
const mcp9808 = require('mcp9808-temperature-sensor');

mcp9808.open().then(sensor =>
  sensor.temperature().
  then(temp => console.log(temp.celsius + '°C')).
  then(_ => sensor.close())
).catch(console.log);
```
an alternative syntax using the async and await keywords that is likely to be easier to understand is (tested with Node 14):
```js
const mcp9808 = require('mcp9808-temperature-sensor');

async function readTemperature() {
  let sensor = await mcp9808.open();
  let temperature = await sensor.temperature();
  console.log(temperature);
  await sensor.close();
}

readTemperature().catch(function (err) {
  console.log(err);
});
```

**Comment by dachshund-digital** [comment]
Thank you every much!  Greatly appreciated.
